montagram/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'montagram.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'montagram.views.index', name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^reco/', include('reco.urls', namespace="reco")),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),

 )

reco/urls.py
from django.conf.urls import patterns, url

from reco import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^crop/(\d+)/$', views.crop, name='crop'),
    url(r'^choice/$', views.choice, name='choice'),
    url(r'^contrib/$', views.contrib, name='contrib'),
    url(r'^presentation/$', views.presentation, name='presentation'),
    url(r'^result/(\d+)/$', views.result, name='result'),
    url(r'^thanks/$', views.thanks, name='thanks'),
    url(r'^contact/$', views.contact, name='contact'),

)

reco/models.py
from django.db import models
import os
import uuid


def content_file_name(instance, filename):
    f, ext = os.path.splitext(filename)
    return 'pictures/%s%s' % (uuid.uuid4().hex, ext)


def cropped_file_name(instance, filename):
    f, ext = os.path.splitext(filename)
    return 'crop/%s%s' % (uuid.uuid4().hex, ext)


class Mountain(models.Model):
    name = models.CharField(max_length=100)


class Mountpic(models.Model):
    mount = models.ForeignKey(Mountain, null=True)
    picture = models.ImageField(upload_to=content_file_name)
    croppic = models.ImageField(upload_to=cropped_file_name)

reco/forms.py
from django import forms
from PIL import Image
import imghdr

class UploadImageForm(forms.Form):
    picture = forms.ImageField()


    def clean_picture(self):
        data = self.cleaned_data['picture']
        if imghdr.what(data) == 'gif':
            raise forms.ValidationError(".gif extension is not supported.")
        return data


class ContribImageForm(forms.Form):
    name = forms.ChoiceField()
    other = forms.CharField(required=False)
    picture = forms.ImageField()

    def clean_picture(self):
        data = self.cleaned_data['picture']
        if imghdr.what(data) == 'gif':
            raise forms.ValidationError(".gif extension is not supported.")
        return data
        
    def clean(self):
        cleaned_data = super(ContribImageForm, self).clean()
        name = cleaned_data.get("name")
        other = cleaned_data.get("other")
        if name == '0' and not other:
            raise forms.ValidationError("Other is a required field if selected in Name.")
        return cleaned_data


class CropFileForm(forms.Form):
    x1 = forms.DecimalField()
    x2 = forms.DecimalField()
    y1 = forms.DecimalField()
    y2 = forms.DecimalField()

montagram/views.py
from django.shortcuts import render

def index(request):
	return render(request, 'montagram/index.html')

reco/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, render, redirect
from reco.forms import ContribImageForm, CropFileForm, UploadImageForm
from django.template import RequestContext
from reco.models import Mountpic, Mountain
from django.core.urlresolvers import reverse
from PIL import Image
from django import forms
from django.core.files.base import ContentFile
from client import sendjson


def index(request):
    return redirect('/')


def choice(request):
    return render(request, 'reco/choice.html')    


def upload(request):
    form = UploadImageForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        mountpic = Mountpic()
        mountpic.picture = form.cleaned_data['picture']
        mountpic.save()
        return HttpResponseRedirect(reverse('reco:crop', args=(mountpic.id,)))
    return render_to_response('reco/upload.html', {'form': form}, context_instance=RequestContext(request))


def contrib(request):
    form = ContribImageForm(request.POST or None, request.FILES or None)
    form.fields['name'] = forms.ChoiceField(choices=get_mountains_name())
    if form.is_valid():
        mountpic = Mountpic()
        if form.cleaned_data['name'] !='0':
            mount = Mountain.objects.get(id=form.cleaned_data['name'])
        else:
            mount = Mountain()
            mount.name = form.cleaned_data['other']
        mountpic.picture = form.cleaned_data['picture']
        mount.save()
        mountpic.mount = mount
        mountpic.save()
        return HttpResponseRedirect(reverse('reco:crop', args=(mountpic.id,)))
    return render_to_response('reco/contrib.html', {'form': form}, context_instance=RequestContext(request))


def crop(request, image_id):
    mountpic = Mountpic.objects.get(id=image_id)
    form = CropFileForm(request.POST or None, request.FILES or None, auto_id=True)
    if form.is_valid():
        x1 = int(round(float(form.cleaned_data['x1']), 0))
        x2 = int(round(float(form.cleaned_data['x2']), 0))
        y1 = int(round(float(form.cleaned_data['y1']), 0))
        y2 = int(round(float(form.cleaned_data['y2']), 0))
        crop_coords = (x1, y1, x2, y2)
        mountpic.croppic.save('crop.jpg', ContentFile(cropper(mountpic.picture.url, crop_coords)), save=True)
        """ if a mountain has a name, it came from contrib"""
        if hasattr(mountpic.mount, 'name'):
            return render(request, "reco/thanks.html")
        else:
            #return render(request, "reco/result.html", sendjson(message))
            return HttpResponseRedirect(reverse('reco:result', args=(mountpic.id,)))

    return render_to_response('reco/crop.html', {'form': form, 'image_id': image_id, 'image': mountpic.picture}, context_instance=RequestContext(request))


def get_mountains_name():
    mountains = Mountain.objects.all()
    mountlist = []
    for mount in mountains:
        mountlist.append((mount.id, mount.name))
    mountlist.append((0, 'Other'))
    return mountlist


def cropper(original_image_url, crop_coords):
    """ Open original, create and return  a new cropped image"""
    import urllib2
    from cStringIO import StringIO
    input_file = StringIO(urllib2.urlopen(original_image_url).read())
    input_file.seek(0)
    img = Image.open(input_file).crop(crop_coords)
    tmp = StringIO()
    img.save(tmp, 'JPEG', )
    tmp.seek(0) 
    input_file.close()
    return tmp.getvalue()


def presentation(request):
    return redirect("http://montagram.insa-lyon.fr")


def result(request, image_id):
    mountpic = Mountpic.objects.get(id=image_id)
    message = {'picture': mountpic.croppic.url, 'name': 'not_defined'}
    result = sendjson(message)
    return render_to_response('reco/result.html', {'image_id': image_id, 'image': mountpic.picture, 'name': result['name'],
                                                   'accuracy1': result['accuracy1'], 'accuracy2': result['accuracy2'], 'accuracy3': result['accuracy3']},
                              context_instance=RequestContext(request))


def thanks(request):
    return render(request, 'reco/thanks.html')


def contact(request):
    return render(request, 'reco/contact.html')

templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--js -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{{ STATIC_URL}}js/jquery.poptrox.min.js"></script>
    <script src="{{ STATIC_URL }}js/skel.min.js"></script>
    {% block js %}
    <script src="{{ STATIC_URL }}js/init.js"></script>
    {% endblock %}

    <!--CSS -->
    
    <link rel="stylesheet" href="{{ STATIC_URL }}css/skel-noscript.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css"/>
    {% block css %}
    {% endblock %}

    <title>{% block title %} Montagram {% endblock %}</title>
    <link rel="icon" href="{{ STATIC_URL }}images/logo1.png" type="image/x-icon">

</head>
<body>
<header id="header">
        <!-- Logo -->
             <h1 id="logo">
                 <a href="{% url 'reco:index' %}">
                     <img src="{{ STATIC_URL }}images/logo1.png" width="30" alt="Responsive image">
                     Montagram</a>
             </h1>

        <!-- Nav -->
            <nav id="nav">
                <ul>
                    <li><a href="{%  url 'reco:upload' %}">Identification</a></li>
                    <li><a href="{%  url 'reco:contrib' %}">Labélisation</a></li>
                    <li><a href="{%  url 'reco:presentation' %}" target="_blank">Documentation</a></li>
                    <li><a href="{%  url 'reco:contact' %}">Contact</a></li>
                </ul>
            </nav>

        <!-- Bitbucket ribbon #hype -->
            <a href="https://bitbucket.org/montagram/montagram" id="ribbon">
              <img src="https://bitbucket.org/zgramana/bitbucket-ribbons/raw/988dffc5fbeb/png/bitbucket-ribbon-gray.png" />

            </a>

</header>



<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
     {% block jumbotron %}{% endblock %}
</div>

<div class="container">



</div>

	{% block script %}{% endblock %}


<footer id="footer">
					<ul class="menu" id="logo"><a href="https://telecom.insa-lyon.fr/">
						<img src="{{ STATIC_URL }}images/insa-blanc.png" width="60" alt="Responsive image">
						<li> Département  Télécommunications <br/>
						 Services et Usages</li>
						</a>
					</ul>

				<!--
				     Social Icons

				     Use anything from here: http://fortawesome.github.io/Font-Awesome/cheatsheet/)
				-->

				<!-- Menu -->
					<ul class="menu">
						<li>&copy; Oriane Blot - Léa Le Baron - Baptiste Desbiolles <br/>
						Adrien Mallecourt - Augustin Renard - Augustin Roux - 2014</li>
						<li>Design: <a href="http://html5up.net">HTML5 UP</a>
                            <br />
                            <a href={% url 'reco:contact' %} >Contact</a></li>
					</ul>

			</footer>
</body>
</html>

templates/montagram/index.html
{% extends "base.html" %}

{% block title %}Montagram{% endblock %}

{% block jumbotron %}
    <section id="two" class="main style1 dark fullscreen">
         <div>
            <h2>Bienvenue sur Montagram</h2>
             <p><em>Outil d'identification de sommets</em></p>
            <p><a href="{% url 'reco:choice' %}" class="button style2" role="button">Commencer &raquo;</a></p>
         </div>
    </section>
{% endblock %}

templates/reco/choice.html
{% extends "base.html" %}

{% block title %}Montagram - Choix{% endblock %}

{% block jumbotron %}
    <section id="one" class="main style3 dark fullscreen">
        <div class="box">
            <p><a href="{% url 'reco:upload' %}" class="button style2" role="button"> Reconnaître le sommet &raquo;</a></p>
            <p><a href="{% url 'reco:contrib' %}" class="button style2" role="button"> Labéliser un sommet &raquo;</a></p>
            <p class="comment">
                Montagram vous permet de reconnaître des sommets. Identifiez une de vos photos ou collaborez à
                l'enrichissement de notre base de données en ajoutant un sommet connu.
            </p>
        </div>
    </section>
{% endblock %}

templates/reco/contact.html
{% extends "base.html" %}

{% block title %}Montagram - Contact{% endblock %}

{% block jumbotron %}
    <section id="twobis" class="main style1 dark fullscreen">
        <div class="container">
            <p>
                Ce projet a été élaboré dans le cadre du Projet Innovant du département
                <a href="http://tc-pi.insa-lyon.fr/" target="_blank" title="TC - INSA Lyon"> Télécommunications de l’INSA de Lyon</a>.
                <br />
                Consultez la <a href="http://montagram.insa-lyon.fr/" target="_blank" title="Montagram - Documentation">documentation</a>
                pour plus d'informations.
            <hr />
            <p><a href="mailto:contactmontagram@gmail.com">Envoyez-nous un email !</a></p>
        </div>
    </section>
{% endblock %}

templates/reco/contrib.html
{% extends "base.html" %}

{% block title %}Montagram - Contribution{% endblock %}

{% block js %}
{% endblock %}

{% block jumbotron %}
    <section id="work" class="main style3 dark fullscreen">
        <div class="box">
            <p class="comment">
                Sélectionnez une photo du pic montagneux que vous souhaitez labéliser.
                Vous pouvez choisir des photos par tout temps, tant que le sommet est clairement reconnaissable.
            </p>
             <script type="text/javascript">
             // The other field appears only if other is selected

             $(document).ready(function(){
                $("#id_name").change(function(){
                   if ($(this).val() == "0" ) {
                      $("#id_other").slideDown("fast"); //Slide Down Effect

                   } else {

                      $("#id_other").slideUp("fast");    //Slide Up Effect

                   }
                });
             });
             </script>
            <form method="POST" enctype="multipart/form-data" action=".">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="input select">
                   <p>
                   {{ form.name.errors }}
                   <label for="id_name">Nom du sommet:</label>
                   {{ form.name }}
                   </p>
                </div>
                <div class="myhide" id="id_other">
                   {{ form.other.errors }}
                   <label for="id_other">Entrez le nom:</label>
                   {{ form.other }}
                </div>
                <div class="id_picture">
                   <p>
                   {{ form.picture.errors }}
                   <label for="id_picture">Image:</label>
                   {{ form.picture }}
                   </p>
                </div>
                <input type="submit" value="Ajouter" class="button style2" />
            </form>
        </div>
    </section>
{% endblock %}

templates/reco/crop.html
{% extends "base.html" %}

    {% block js %}
    <script src="{{ STATIC_URL}}js/jquery.Jcrop.js"></script>
    {% endblock %}
    {% block css %}
    <link rel="stylesheet" href="{{ STATIC_URL}}css/jquery.Jcrop.css" type="text/css" />
    {% endblock %}


{% block title %}Montagram - Découpage{% endblock %}

{% block jumbotron %}
    <section id="intro" class="main style3 dark fullscreen">
        <div class="box-big">
          <p>Sélection de la photo</p>
            <img style="width: 100%" src={{ image.url }} id="target">
        <script type="text/javascript">
         jQuery(function($){

            var jcrop_api;

            $('#target').Jcrop({
              onChange:   showCoords,
              onSelect:   showCoords,
              onRelease:  clearCoords,
              setSelect:   [ 200, 200, 100, 100 ],
              aspectRatio: 1,
              boxHeight: 400,
            },function(){
              jcrop_api = this;
            });

            $('#coords').on('change','input',function(e){
              var x1 = $('#x1').val(),
                  x2 = $('#x2').val(),
                  y1 = $('#y1').val(),
                  y2 = $('#y2').val();
              jcrop_api.setSelect([x1,y1,x2,y2]);
            });

          });

          // Simple event handler, called from onChange and onSelect
          // event handlers, as per the Jcrop invocation above
          function showCoords(c)
          {
            $('#x1').val(c.x);
            $('#y1').val(c.y);
            $('#x2').val(c.x2);
            $('#y2').val(c.y2);
          };

          function clearCoords()
          {
            $('#coords input').val('');
          };

        </script>

          <br>

          <form id="coords" class="coords" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="myhide" id="id_x1">
              {{ form.x1.errors }}
                <label for="id_x1"></label>
                {{ form.x1 }}
            </div>
            <div class="myhide" id="id_x2">
              {{ form.x2.errors }}
                <label for="id_x2"></label>
                {{ form.x2 }}
            </div>
            <div class="myhide" id="id_y1">
              {{ form.y1.errors }}
                <label for="id_y1"></label>
                {{ form.y1 }}
            </div>
            <div class="myhide" id="id_y2">
              {{ form.y2.errors }}
                <label for="id_other"></label>
                {{ form.y2 }}
            </div>
            <div class="comment">
                <strong>Instructions</strong>
                <p>
                    Dessinez un cadre assez large autour du sommet à identifier.
                    <br />
                    Placez le sommet bien au centre.
                </p>
            </div>
            <input type="submit" value="Valider" class="button style2"/>
            </form>
        </div>
    </section>
{% endblock %}

templates/reco/result.html
{% extends "base.html" %}

{% block title %}Montagram - Résultat{% endblock %}

{% block jumbotron %}
    <section id="four" class="main style3 dark fullscreen">
        <div class="box-big">
            <h1>{{ name }}</h1>
            <a class="info-link" href="#infos" style="color: #000000">plus d'infos</a>
            <img src="{{ image.url }}" alt="Result" style="width: 100%">
            <div id="infos">
                <p style="line-height: 3em">
                    <br />
                </p>
                <hr />
                <strong>Infos</strong>
                {% if accuracy2 == 0 %}
                    <p>
                        Notre algorithme a pu identifier le sommet avec une précision de {{ accuracy1 }}%.
                        <br />
                        <br />
                        Vous pensez qu'il s'agit d'une erreur ? Contactez-nous par
                        <a href="mailto:contactmontagram@gmail.com?subject=Result error - picture {{ image_id }}
                        &amp;body=Précision: {{ name }} - {{ accuracy1 }}" style="color: #000000">mail</a> !
                    </p>
                {% else %}
                    <p>
                        Nous n'avons pas pu identifier votre photo de manière précise.
                    </p>
                    <ul>
                        <li>Cervin : {{ accuracy1 }}%</li>
                        <li>Huayna Picchu : {{ accuracy2 }}%</li>
                        <li>Département TC : {{ accuracy3 }}%</li>
                    </ul>
                    <p>
                        Vous n'avez pas de doute sur le nom du sommet ? Pensez à le
                        <a style="color: #000000" href="{%  url 'reco:contrib' %}">labéliser</a> !
                    </p>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

templates/reco/thanks.html
{% extends "base.html" %}

{% block title %}Montagram - Merci{% endblock %}

{% block jumbotron %}
    <section id="three" class="main style3 dark fullscreen">
        <div style="padding: 8em 0 10em 0; padding-left: 22%; line-height: 1.1em">
            <h1>Merci d’avoir contribué au développement du projet Montagram.</h1>
            <p>Votre photo sera validée par un administrateur.</p>
        </div>
    </section>
{% endblock %}

templates/reco/upload.html
{% extends "base.html" %}


{% block title %}Montagram - Sélection{% endblock %}


{% block jumbotron %}
    <section id="onebis" class="main style1 dark fullscreen" xmlns="http://www.w3.org/1999/html">
        <div class="box">
            <form method="POST" enctype="multipart/form-data" action=".">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="style2">
                   <p>
                   {{ form.picture.errors }}
                   <label for="id_picture">Image:</label>
                   {{ form.picture }}
                   </p>
                </div>
                <p style="font-size: small; line-height: 1em">
                    <strong>Attention</strong>
                    <br />
                    Choississez une photo où le sommet de la montagne se distingue du reste du massif.
                </p>
                <input type="submit" value="Ajouter &raquo;" class="button style2" />
            </form>
        </div>
    </section>
{% endblock %}